name: 自动部署Netlify
on:
  push:
    branches: [ main ] #只有main分支提交才自动部署
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库全部代码
        uses: actions/checkout@v4

      - name: 部署网站到Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./ #网站文件在根目录，不用改
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
